### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by codenyte** [libredirect/frontends_manager#2]
A macOS version of the frontend manager would be pretty nice, especially when core features like [Skip offline instances](https://github.com/libredirect/browser_extension/issues/702) are not implemented in the browser extension and [users are told to use the frontend manager instead](https://github.com/libredirect/browser_extension/issues/686#issuecomment-1547423026).

**Comment by ManeraKai** [comment]
Well if I have a Macbook to compile and test on but I don't. Any community help would help

**Comment by ManeraKai** [comment]
Maybe you can still help, our concerns are two things:
1. this [file](https://github.com/libredirect/frontends_manager/blob/main/src/services/binary_frontends.js), you can see how we change the code a little if we are on windows or linux:
![image](https://github.com/libredirect/frontends_manager/assets/40805353/5a7cc25b-0052-4586-abec-71ac9fd1d4be)
![image](https://github.com/libredirect/frontends_manager/assets/40805353/3e8d7547-8b76-4cd6-b06f-2a463aec286e)
It's mostly that linux has a different binary file name than windows and other things for unzipping, but MacOS is a Unix system so it will be very similar to the linux commands.
2. [frontends_binaries](https://github.com/libredirect/frontends_binaries), this one I can fix myself but you should test out the binaries.

**Comment by xbdmHQ** [comment]
> Well if I had a Macbook to compile and test on but I don't. Any community help would help.

MacOS VM: https://developer.apple.com/documentation/virtualization/installing_macos_on_a_virtual_machine
