### ISSUE TITLE
Add podman support

### ISSUE THREAD

**Issue by raShMan777** [libredirect/frontends_manager#3]
I have podman installed and not docker. It would be nice if podman would be supported. They behave more or less identical apart from having to use the podman instead of the docker binary. („Podman provides a command line interface (CLI) familiar to anyone who has used the Docker [Container Engine](https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction/#h.6yt1ex5wfo3l). Most users can simply alias Docker to Podman (alias docker=podman) without any problems.“ - https://docs.podman.io/en/latest/index.html) I also think it's a better alternative given docker's license and podman not wanting to sell stuff to me.

**Comment by ManeraKai** [comment]
Removed docker.
