### ISSUE TITLE
Docker not running / Missing docs

### ISSUE THREAD

**Issue by Lippiece** [libredirect/frontends_manager#6]
I'm using the appimage.

Can you please explain how to use this tool? The initial problem was about keeping cookies across SearXNG instances. In another issue, a maintainer stated that this issue should be addressed with frontends_manager. 

However, I don't see any docs or explanation on how to use it. Under SearXNG there is `Docker not running`.

Edit: Seems like the appimage needs to be run with sudo.

**Comment by Lippiece** [comment]
I've managed to run SearXNG instance with sudoing the appimage, but searching libredirect leads to http://searxng.localhost:8080/?q=myquery and returns 502.

If this needs another issue, I'll open it.

**Comment by ManeraKai** [comment]
You should install Docker Desktop, and no it doesn't need sudo.

**Comment by Lippiece** [comment]
OK, I did that.

<details>

![Screenshot from 2023-09-08 22-27-52](https://github.com/libredirect/frontends_manager/assets/47634624/e88c24de-04cd-41f0-9399-3deb5fab23e3)
![Screenshot from 2023-09-08 22-26-53](https://github.com/libredirect/frontends_manager/assets/47634624/11c2537a-fe62-411e-960d-0eca662cbb3e)

</details>

**Comment by ManeraKai** [comment]
Removed docker. It's giving a lot of problems.
