### ISSUE TITLE
Unable to download/use Nitter frontend

### ISSUE THREAD

**Issue by hadi-naqvi** [libredirect/frontends_manager#8]
Using the Linux ``.AppImage`` (the ``.deb`` installs but doesn't run so using this instead) and any time I click "Download" for Nitter, it instantly downloads and allows me to run it, which doesn't actually work. If I click "refresh" it simply gives me the option to download again as if I never downloaded it in the first place.

**Comment by ManeraKai** [comment]
Nitter got discontinued.
