### ISSUE TITLE
Swap Libreddit for Redlib

### ISSUE THREAD

**Issue by Victor239** [libredirect/frontends_manager#9]
I've been using a personal Libreddit for a few months now and it's been working great, however as of today it seems to no longer work with Reddit. It's time to swap over to the maintained fork Redlib https://github.com/libredirect/browser_extension/issues/879

**Comment by ManeraKai** [comment]
https://github.com/libredirect/frontends_manager/commit/ae85586f0a39c507cece615eee5c03e4a5f3e5a7
